import type {ComponentConfig, VisualItem} from "../../schemas/components";

const scriptPath =
  "/Volumes/Laohu_Work/项目/老胡/老胡自媒体/老胡文稿/01_初稿/2026-09-02_MiniMax-H3真正用法_教学视频制作脚本.md";

const items = (
  section: string,
  values: Array<Omit<VisualItem, "source" | "status"> & {status?: VisualItem["status"]}>,
): VisualItem[] => values.map((item) => ({
  status: "default",
  ...item,
  source: {type: "source-doc", confidence: "confirmed", ref: `${scriptPath}#${section}`},
}));

const overlay = (order: number, hostCarrier: "SCREEN_RECORDING" | "EVIDENCE" | "BASE") => ({
  groupId: "h3-tutorial",
  order,
  role: "EXPLANATION" as const,
  hostCarrier,
  persistence: "SEGMENT" as const,
  stateBefore: "本段关系尚未建立",
  stateUpdate: "跟随口播逐步点亮当前关系",
  stateAfter: "结论保持一秒后交回真实录屏",
  contrastMode: "FULL_SCRIM" as const,
  contrastReason: "知识动画出现时统一压暗整个真实画面，保留上下文轮廓，同时把视觉焦点交给关系动画",
  attentionPlan: [{
    spokenCue: "本段核心判断出现",
    focusOwner: "OVERLAY" as const,
    target: "正在解释的关系",
    reason: "录屏能证明对象存在，叠层负责把关系讲清楚",
  }],
  protectedRegions: [
    {target: "SOURCE_UI" as const, description: "工作流节点名称与参数值不得遮挡"},
    {target: "SUBTITLES" as const, description: "底部中文字幕安全区"},
  ],
  handoff: "关系完整后淡出，观众继续看真实工作流",
});

const base = {
  motionIntensity: "medium",
  renderMode: "asset",
  presentation: "overlay",
  stylePreset: "editorial-dark",
  emotionalTone: "clear",
} as const;

export const h3TutorialConfigs: Record<
  | "ratioLock"
  | "samplingChain"
  | "latentTransfer"
  | "taskModelChoice"
  | "finalRecap"
  | "missingOpeningEvidence"
  | "missingSameTaskComparison"
  | "missingControlledStrengthComparison",
  ComponentConfig
> = {
  ratioLock: {
    ...base,
    component: "CompareTransform",
    mode: "wrong-right",
    placement: "right",
    accentRole: "warning",
    kicker: "H3 / PARAMETER RELATION",
    title: "一采比例 = 二采比例",
    subtitle: "先保持画幅一致，再逐步提高分辨率",
    conclusion: "先跑通，再往上调",
    communicationGoal: "guide",
    informationShape: "comparison",
    durationInFrames: 240,
    sourceTimeRange: {start: 142.22, end: 150.22},
    overlayContinuity: overlay(1, "SCREEN_RECORDING"),
    items: items("S04 小白部分：画幅、分辨率和运行档位", [
      {id: "wrong", label: "画幅不一致", description: "一采横屏 / 二采竖屏", status: "negative"},
      {id: "right", label: "比例锁定", description: "一采与二采使用同一画幅", status: "positive"},
      {id: "safe", label: "先跑通", description: "从当前可运行参数开始", status: "active"},
      {id: "risk", label: "再提高", description: "进入高分辨率前先观察稳定性"},
    ]),
    links: [],
    highlightOrder: ["wrong", "right", "safe", "risk"],
  },
  samplingChain: {
    ...base,
    component: "FlowNodeGraph",
    mode: "linear",
    placement: "right",
    accentRole: "technical",
    kicker: "SIGMA / ONE CHAIN",
    title: "不是两次生成",
    subtitle: "一采在中途停下，二采沿同一条采样链继续到 0",
    conclusion: "一采定结构，二采补细节",
    communicationGoal: "explain",
    informationShape: "sequence",
    durationInFrames: 360,
    sourceTimeRange: {start: 230, end: 242},
    overlayContinuity: overlay(2, "SCREEN_RECORDING"),
    items: items("S06 核心原理：一采定结构，二采补细节", [
      {id: "start", label: "完整采样轨道", description: "目标终点是 0", revealAtFrame: 20},
      {id: "first", label: "一采中途停下", description: "先锁定人物、动作与构图", status: "active", revealAtFrame: 70},
      {id: "handoff", label: "同一状态继续", description: "不重新生成第二条链", revealAtFrame: 140},
      {id: "second", label: "二采补全细节", description: "脸、服装、皮肤与道具逐层清晰", status: "positive", revealAtFrame: 210},
    ]),
    links: [
      {from: "start", to: "first"},
      {from: "first", to: "handoff"},
      {from: "handoff", to: "second"},
    ],
    highlightOrder: ["start", "first", "handoff", "second"],
  },
  latentTransfer: {
    ...base,
    component: "FlowNodeGraph",
    mode: "artifact-flow",
    placement: "right",
    accentRole: "danger",
    kicker: "LATENT / DO NOT BREAK",
    title: "必须传同一份 Latent",
    subtitle: "接错输出，二采就无法继承一采定下来的结构",
    conclusion: "一采未完成 Latent → 放大 → 二采继续",
    communicationGoal: "warn",
    informationShape: "sequence",
    durationInFrames: 360,
    sourceTimeRange: {start: 273.5, end: 285.5},
    overlayContinuity: overlay(3, "SCREEN_RECORDING"),
    items: items("S07 最容易接错的地方：Latent传递", [
      {id: "latent", label: "一采未完成 Latent", description: "保留人物、动作与构图", status: "active", revealAtFrame: 18},
      {id: "denoise", label: "实际输出节点", description: "名称以真实界面为准", revealAtFrame: 75},
      {id: "upscale", label: "潜空间放大", description: "规定最终尺寸或放大倍率", revealAtFrame: 135},
      {id: "second", label: "二采继续采样", description: "沿同一状态补全细节", revealAtFrame: 205},
      {id: "result", label: "最终视频", description: "结构延续，细节完成", status: "positive", revealAtFrame: 275},
    ]),
    links: [
      {from: "latent", to: "denoise"},
      {from: "denoise", to: "upscale"},
      {from: "upscale", to: "second"},
      {from: "second", to: "result"},
    ],
    highlightOrder: ["latent", "denoise", "upscale", "second", "result"],
  },
  taskModelChoice: {
    ...base,
    component: "FlowNodeGraph",
    mode: "branch",
    placement: "left",
    accentRole: "success",
    kicker: "MODEL / TASK FIRST",
    title: "先看任务，再选模型",
    subtitle: "不是谁的画质最高，而是谁负责声音与口型",
    conclusion: "根据任务选模型，不按单一画质排名",
    communicationGoal: "choose",
    informationShape: "network",
    durationInFrames: 360,
    sourceTimeRange: {start: 673.2, end: 685.2},
    overlayContinuity: overlay(4, "SCREEN_RECORDING"),
    items: items("S11 数字人为什么使用另一套模型", [
      {id: "task", label: "先判断音频来源", description: "模型是否还要负责生成声音", status: "active", revealAtFrame: 18},
      {id: "multi", label: "多参考视频", description: "模型同时生成声音", revealAtFrame: 80},
      {id: "multiGoal", label: "优先情绪与重音", description: "清晰但软弱仍可能失败", revealAtFrame: 145},
      {id: "avatar", label: "数字人", description: "外部音频已经确定表达", revealAtFrame: 80},
      {id: "avatarGoal", label: "优先清晰与稳定", description: "模型负责画面与口型", status: "positive", revealAtFrame: 145},
    ]),
    links: [
      {from: "task", to: "multi"},
      {from: "multi", to: "multiGoal"},
      {from: "task", to: "avatar"},
      {from: "avatar", to: "avatarGoal"},
    ],
    highlightOrder: ["task", "multi", "multiGoal", "avatar", "avatarGoal"],
  },
  finalRecap: {
    ...base,
    component: "TimelineRoadmap",
    mode: "phases",
    placement: "center",
    accentRole: "info",
    kicker: "H3 / RECAP",
    title: "一条链，两个阶段",
    subtitle: "把今天真正需要记住的关系收回来",
    conclusion: "结构先定，细节后补；模型跟着任务走",
    communicationGoal: "review",
    informationShape: "sequence",
    durationInFrames: 210,
    sourceTimeRange: {start: 706.6, end: 713.6},
    overlayContinuity: overlay(5, "BASE"),
    items: items("S12 总结与下期预告", [
      {id: "input", label: "输入素材", revealAtFrame: 12},
      {id: "first", label: "一采定结构", status: "active", revealAtFrame: 42},
      {id: "latent", label: "Latent 传递", revealAtFrame: 72},
      {id: "second", label: "二采补细节", revealAtFrame: 102},
      {id: "model", label: "按任务选模型", status: "positive", revealAtFrame: 132},
    ]),
    links: [
      {from: "input", to: "first"},
      {from: "first", to: "latent"},
      {from: "latent", to: "second"},
      {from: "second", to: "model"},
    ],
    highlightOrder: ["input", "first", "latent", "second", "model"],
  },
  missingOpeningEvidence: {
    ...base,
    component: "EditorialOverlayShell",
    mode: "evidence-dock",
    placement: "center",
    accentRole: "warning",
    kicker: "PLACEHOLDER / OPENING",
    title: "待补｜真实结果 2–3 段",
    subtitle: "这里必须替换成同一工作流的真实生成结果，不用动画冒充证据",
    conclusion: "替换后再交付",
    communicationGoal: "prove",
    informationShape: "hierarchy",
    durationInFrames: 132,
    sourceTimeRange: {start: 0, end: 4.4},
    overlayContinuity: {...overlay(6, "BASE"), role: "EVIDENCE"},
    items: items("S01 真实结果与正式开场", [
      {id: "result", label: "真实成片", description: "2–3 个可代表效果的结果", status: "active"},
      {id: "record", label: "运行记录", description: "时长与耗时必须能核验"},
    ]),
    links: [],
    highlightOrder: ["result", "record"],
  },
  missingSameTaskComparison: {
    ...base,
    component: "EditorialOverlayShell",
    mode: "evidence-dock",
    placement: "right",
    accentRole: "warning",
    kicker: "PLACEHOLDER / S08",
    title: "待补｜同一次任务 A/B",
    subtitle: "一采中间预览与二采最终结果必须来自同一任务",
    conclusion: "不同素材不能拼成伪对比",
    communicationGoal: "prove",
    informationShape: "comparison",
    durationInFrames: 150,
    sourceTimeRange: {start: 408.3, end: 413.3},
    overlayContinuity: {...overlay(7, "EVIDENCE"), role: "EVIDENCE"},
    items: items("S08 双时钟与中间预览", [
      {id: "first", label: "一采预览", description: "只看结构"},
      {id: "second", label: "二采成片", description: "再看音画同步", status: "active"},
    ]),
    links: [],
    highlightOrder: ["first", "second"],
  },
  missingControlledStrengthComparison: {
    ...base,
    component: "EditorialOverlayShell",
    mode: "evidence-dock",
    placement: "right",
    accentRole: "warning",
    kicker: "PLACEHOLDER / S09",
    title: "待补｜同条件三档对比",
    subtitle: "相同人物、提示词与随机条件，只改变模型强度",
    conclusion: "没有控制变量，只能叫案例",
    communicationGoal: "prove",
    informationShape: "comparison",
    durationInFrames: 180,
    sourceTimeRange: {start: 600.33, end: 606.33},
    overlayContinuity: {...overlay(8, "EVIDENCE"), role: "EVIDENCE"},
    items: items("S09 不油腻的关键：模型组合与强度平衡", [
      {id: "low", label: "偏低", description: "朦胧 / 颗粒感"},
      {id: "balanced", label: "平衡", description: "以实际节点值为准", status: "active"},
      {id: "high", label: "偏高", description: "更锐 / 可能偏油"},
    ]),
    links: [],
    highlightOrder: ["low", "balanced", "high"],
  },
};
