import type {ComponentConfig, VisualItem} from "../../schemas/components";

const controlDoc =
  "模板/remotion-assets/workspace/src/configs/examples/source-material.md";

const sourcedItems = (
  scene: string,
  items: Array<Omit<VisualItem, "source" | "status"> & {status?: VisualItem["status"]}>,
): VisualItem[] =>
  items.map((item) => ({
    status: "default",
    ...item,
    source: {
      type: "source-doc",
      confidence: "confirmed",
      ref: `${controlDoc}#${scene}`,
    },
  }));

const base = {
  motionIntensity: "medium",
  renderMode: "standalone",
  stylePreset: "clear",
} as const;

export const scene001Examples: Record<
  "scene07" | "scene08" | "scene10" | "scene12" | "scene14" | "scene16",
  ComponentConfig
> = {
  scene07: {
    ...base,
    component: "DecisionCanvas",
    mode: "matrix",
    title: "先决定路线，再决定做法",
    subtitle: "路线不是分类，而是你要长期沉淀什么资产",
    conclusion: "新账号前 20 条：1 条主路线 + 1 条辅助路线",
    communicationGoal: "choose",
    emotionalTone: "confident",
    informationShape: "comparison",
    durationInFrames: 360,
    sourceTimeRange: {start: 213.4, end: 320.533},
    items: sourcedItems("场景-07：路线选择", [
      {id: "emotion", label: "情绪歌", description: "沉淀情绪标签｜看评论共鸣", status: "active"},
      {id: "trend", label: "热点改编", description: "沉淀热点反应｜看传播速度"},
      {id: "ip", label: "人设 IP", description: "沉淀人物识别｜看粉丝记忆"},
      {id: "tutorial", label: "教程种草", description: "沉淀信任资产｜看收藏转化"},
      {id: "visual", label: "视觉审美", description: "沉淀风格资产｜看停留完播"},
      {id: "matrix", label: "批量矩阵", description: "沉淀工作流｜看测试效率"},
    ]),
    links: [],
    highlightOrder: ["emotion", "tutorial"],
  },
  scene08: {
    ...base,
    component: "FormTemplateBuilder",
    mode: "form-fill",
    title: "选题是流量起点，不是歌词起点",
    subtitle: "先问：谁在什么场景下，需要这首歌替他说话？",
    conclusion: "有效选题 = 人群 + 情绪 + 场景 + 画面 + 标题",
    communicationGoal: "guide",
    emotionalTone: "satisfying",
    informationShape: "transformation",
    durationInFrames: 300,
    sourceTimeRange: {start: 320.533, end: 384.8},
    items: sourcedItems("场景-08：选题公式", [
      {id: "audience", label: "给谁听", description: "先锁定具体人群"},
      {id: "emotion", label: "打中什么情绪", description: "说清楚需要被表达的感受"},
      {id: "scene", label: "发生在哪个场景", description: "让观众能够代入自己"},
      {id: "visual", label: "3 秒画面", description: "第一眼就能看懂主题"},
      {id: "title", label: "发布标题", description: "直接写出人群、场景和情绪"},
    ]),
    links: [],
    highlightOrder: ["audience", "emotion", "scene", "visual", "title"],
  },
  scene10: {
    ...base,
    component: "FunnelJourney",
    mode: "attention",
    title: "画面让人停下，视频让人看完并互动",
    subtitle: "先跑通画面和音乐的连接，再追求精修",
    conclusion: "不要一上来炫技，先完成最小传播闭环",
    communicationGoal: "explain",
    emotionalTone: "energetic",
    informationShape: "sequence",
    durationInFrames: 300,
    sourceTimeRange: {start: 456, end: 544.5},
    items: sourcedItems("场景-10：画面视频", [
      {id: "stop", label: "3 秒停留", description: "动态歌词或清晰画面先让人停下", value: 3},
      {id: "finish", label: "继续看完", description: "内容推进与音乐节奏保持连接", value: 2},
      {id: "interact", label: "点赞评论", description: "让观众有情绪和观点可以回应", value: 1},
      {id: "review", label: "复盘优化", description: "从反馈里决定下一条改什么", value: 1},
    ]),
    links: [],
    highlightOrder: ["stop", "finish", "interact", "review"],
  },
  scene12: {
    ...base,
    component: "DataStoryChart",
    mode: "dashboard",
    title: "复盘不是写感想，而是决定下一条改什么",
    subtitle: "看观察窗口、看关键指标，下一条只改一个变量",
    conclusion: "下一条只改一个变量：标题 / 副歌 / 封面 / 画面形式",
    communicationGoal: "review",
    emotionalTone: "confident",
    informationShape: "timeline",
    durationInFrames: 300,
    sourceTimeRange: {start: 596.4, end: 660.2},
    items: sourcedItems("场景-12：数据复盘", [
      {id: "2h", label: "2h 初始反馈", description: "先看发布后的第一轮信号", value: 2},
      {id: "24h", label: "24h 停留互动", description: "检查完播、互动、收藏和评论", value: 24, status: "active"},
      {id: "72h", label: "72h 继续扩散", description: "判断内容是否还在获得传播", value: 72},
    ]),
    links: [],
    highlightOrder: ["2h", "24h", "72h"],
    supportingLabels: ["完播", "互动", "收藏", "评论关键词"],
  },
  scene14: {
    ...base,
    component: "FlowNodeGraph",
    mode: "artifact-flow",
    title: "每一步，都要留下产物",
    subtitle: "产物不是文件列表，而是下一步工作的输入",
    conclusion: "复盘表继续流向下一条优化",
    communicationGoal: "guide",
    emotionalTone: "satisfying",
    informationShape: "sequence",
    durationInFrames: 300,
    sourceTimeRange: {start: 697, end: 752.4},
    items: sourcedItems("场景-14：留下产物", [
      {id: "topic", label: "选题卡", description: "决定方向"},
      {id: "lyrics", label: "歌词稿", description: "决定表达"},
      {id: "music", label: "音乐版本包", description: "决定听感"},
      {id: "visual", label: "画面方案", description: "决定停留"},
      {id: "video", label: "视频成片", description: "决定完播"},
      {id: "publish", label: "发布包", description: "决定点击"},
      {id: "review", label: "复盘表", description: "决定下一条怎么改"},
      {id: "next", label: "下一条优化", description: "只改变一个关键变量", status: "active"},
    ]),
    links: ["topic", "lyrics", "music", "visual", "video", "publish", "review"].map((from, index, ids) => ({
      from,
      to: index === ids.length - 1 ? "next" : ids[index + 1],
    })),
    highlightOrder: ["topic", "lyrics", "music", "visual", "video", "publish", "review", "next"],
  },
  scene16: {
    ...base,
    component: "RiskActionLoop",
    mode: "compliance",
    title: "能做出来，不代表可以随便用",
    subtitle: "风险、规避动作和留痕文件必须一一对应",
    conclusion: "长期做账号的底线：能核验，也能追溯",
    communicationGoal: "warn",
    emotionalTone: "urgent",
    informationShape: "sequence",
    stylePreset: "warning",
    durationInFrames: 330,
    sourceTimeRange: {start: 795.1, end: 863.5},
    items: sourcedItems("场景-16：授权规则", [
      {id: "tool", label: "免费工具授权", description: "核验商用范围", result: "授权记录"},
      {id: "ai", label: "AI 标识要求", description: "按平台要求标注", result: "标识截图"},
      {id: "portrait", label: "肖像声音使用", description: "不冒用真人", result: "授权证明"},
      {id: "asset", label: "素材来源", description: "保存来源链接", result: "素材来源表"},
      {id: "process", label: "生成过程", description: "保存工程文件", result: "生成记录"},
    ]),
    links: [],
    highlightOrder: ["tool", "ai", "portrait", "asset", "process"],
  },
};
